name: CI
on: [push]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm i && npm run build && npx -y vsce package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: "*.vsix"
